export enum Mode {
  MOVIE_GENRE_SELECTION = 'MOVIE_GENRE_SELECTION',
  MOVIE_SELECTION = 'MOVIE_SELECTION',
  MOVIE_SELECTED = 'MOVIE_SELECTED',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  STREAM_SELECTION = 'STREAM_SELECTION',
}